### ISSUE TITLE
still issues about generate data .

### ISSUE THREAD

**Issue by Myzhencai** [lvsn/deeptracking#9] opened 2018-01-25 13:48 UTC
hi, @MathGaron as you mentioned that I need to have a look of the Opengl and I do reinstall everything in a new computer but i still get the same issues .here in pic1 I used to test the opengl it is fine:
![default](https://user-images.githubusercontent.com/21084423/35390528-beac1154-0216-11e8-8290-dc45c90fb6d2.png)
 and then i run it with the skull ply files then i get this : with no error no warning and what I think it can not be the json file issue as you can see in the picture .could it be the issue of plyparser or any thing you do not mention in the project?BTW,could you share the workflow of install dependences or just share the generated data .That can be of great help with my issue.
![default](https://user-images.githubusercontent.com/21084423/35390599-0132a89e-0217-11e8-9c63-cc7f3129e757.png)
![default](https://user-images.githubusercontent.com/21084423/35391055-77f7f622-0218-11e8-8fd7-e3d0d95c6320.png)

and in the plyparser.py this part never used in the code why should we import PlyElement?
wish for your feedback,I only have just 3 days for  the project .
btw,can the generate black picture be the training data as it cotains the pose information?
"""
@staticmethod
    def save_points(points, path):
        vertex = np.zeros(points.shape[0], dtype=([('x', 'f4'), ('y', 'f4'), ('z', 'f4')]))
        vertex.fill(255)
        vertex['x'] = points[:, 0]
        vertex['y'] = points[:, 1]
        vertex['z'] = points[:, 2]
        el = PlyElement.describe(vertex, 'vertex')
        PlyData([el], text=ascii).write(path)
"""

**Comment by Myzhencai** [comment] 2018-01-25 14:23
![default](https://user-images.githubusercontent.com/21084423/35392885-312b5a94-021e-11e8-89da-55811c3e232e.png)
When i add the print(rgbB), I got this things

**Comment by MathGaron** [comment] 2018-01-25 14:50
you can view the images with matplotlib or cv2.imshow, it is easier than looking at the print.
```python
cv2.imshow("test", rgb[:, :, ::-1])
cv2.waitKey()
# or
plt.imshow(rgb)
plt.show()
plt.imshow(depth)
plt.show()
```
I am sorry but I can hardly send you an already generated dataset right now, I am working on another version and approaching a deadline.

That said, it seems that most of your setup works, but it seems like the 3D model is not loaded. Your json files seem also fine.

You could try this [camera.json](https://gist.github.com/MathGaron/64c6c633dd2ee03f30eaa24aeb73b443) file instead : 

You can verify that in [modelrenderer.py](https://github.com/lvsn/deeptracking/blob/5ae0e28c936111cd43255ecbc71c8c9a5f1f6105/deeptracking/data/modelrenderer.py), setup buffer, the vertex information are properly loaded.

**Comment by Myzhencai** [comment] 2018-01-26 00:12
@MathGaron ,thanks for help.I will  try something more with your suggestions.Have a nice day.

**Comment by Myzhencai** [comment] 2018-01-26 12:14
@MathGaron here is the every line start from . i think it is not the issue about your code ,i can be the gpu issue as there are many buffers for gpu ,and my gpu is like this .can you check something unnormal in the workflow.Maybe i need to change another gpu to have a try.BTW,i do changed the camera.json file and it is the same issue and the code to absorbed the change of the json as the widows changed to the size of the camera parameters.looking forward your feedback.thanks : -).
`for model in MODELS:
        vpRender = ModelRenderer(model["model_path"], SHADER_PATH, dataset.camera, window, window_size)
        vpRender.load_ambiant_occlusion_map(model["ambiant_occlusion_model"])`
![default](https://user-images.githubusercontent.com/21084423/35439258-ea766b9a-02d4-11e8-9d52-845f859612f0.png)


![2018-01-26 10 26 20](https://user-images.githubusercontent.com/21084423/35439052-1f70fbfe-02d4-11e8-96b5-63e76551549a.png)
![2018-01-26 10 27 04](https://user-images.githubusercontent.com/21084423/35439053-1fc0b306-02d4-11e8-95b9-a5cf3574f9e2.png)
![2018-01-26 10 28 58](https://user-images.githubusercontent.com/21084423/35439054-200c37f4-02d4-11e8-9bd1-b66e6d411a3c.png)
![2018-01-26 10 48 21](https://user-images.githubusercontent.com/21084423/35439055-205e3e46-02d4-11e8-81ee-d5ec8b8097bb.png)
![2018-01-26 11 03 55](https://user-images.githubusercontent.com/21084423/35439056-20b102de-02d4-11e8-8081-906f68a5c3e2.png)
![2018-01-26 11 04 47](https://user-images.githubusercontent.com/21084423/35439057-2101ca84-02d4-11e8-8b92-414cafb890c2.png)
![2018-01-26 11 05 43](https://user-images.githubusercontent.com/21084423/35439058-21561706-02d4-11e8-9982-7b4c40464ebc.png)
![2018-01-26 11 08 36](https://user-images.githubusercontent.com/21084423/35439059-21a2fb7a-02d4-11e8-8b84-ad4f8024112f.png)
![2018-01-26 11 11 09](https://user-images.githubusercontent.com/21084423/35439060-2299fe34-02d4-11e8-900b-8fccfcd14787.png)
![2018-01-26 11 20 26](https://user-images.githubusercontent.com/21084423/35439062-22e9f3f8-02d4-11e8-9de7-8103b4c7062b.png)
![2018-01-26 11 26 58](https://user-images.githubusercontent.com/21084423/35439063-233a5546-02d4-11e8-9ffa-8f2d98b2d85a.png)
![2018-01-26 11 28 42](https://user-images.githubusercontent.com/21084423/35439064-238f8ebc-02d4-11e8-808b-775d46f394d3.png)
![2018-01-26 11 53 11](https://user-images.githubusercontent.com/21084423/35439065-23df5d84-02d4-11e8-9e1a-22f183b347da.png)
![2018-01-26 11 54 13](https://user-images.githubusercontent.com/21084423/35439066-2435a392-02d4-11e8-89c9-5d0fa5e9d0e0.png)
![2018-01-26 11 56 49](https://user-images.githubusercontent.com/21084423/35439067-2488e930-02d4-11e8-9e35-9f1e96454d77.png)
![2018-01-26 12 00 20](https://user-images.githubusercontent.com/21084423/35439068-24dba9fe-02d4-11e8-8ab1-85fa3df3120d.png)
![2018-01-26 12 18 00](https://user-images.githubusercontent.com/21084423/35439069-25336cf2-02d4-11e8-8018-901add24aa17.png)

![2018-01-26 12 53 51](https://user-images.githubusercontent.com/21084423/35439071-25da739e-02d4-11e8-84b7-e3a348e8bfaf.png)
![2018-01-26 12 55 12](https://user-images.githubusercontent.com/21084423/35439072-26311884-02d4-11e8-81b6-414a15b54295.png)
![2018-01-26 14 29 14](https://user-images.githubusercontent.com/21084423/35439074-268250d2-02d4-11e8-933d-5e59cff114de.png)
![2018-01-26 15 57 05](https://user-images.githubusercontent.com/21084423/35439075-26cf81f4-02d4-11e8-9b6f-b552f0947141.png)
![2018-01-26 15 58 26](https://user-images.githubusercontent.com/21084423/35439077-27224024-02d4-11e8-963a-2652bd979bf2.png)
![2018-01-26 16 02 16](https://user-images.githubusercontent.com/21084423/35439078-2776ffb0-02d4-11e8-914a-b996d4a57088.png)
![2018-01-26 16 03 51](https://user-images.githubusercontent.com/21084423/35439079-27c686e8-02d4-11e8-9a1b-94cee2a85cef.png)
![2018-01-26 16 15 53](https://user-images.githubusercontent.com/21084423/35439081-281df482-02d4-11e8-83c6-afbed469baf0.png)
![2018-01-26 16 36 11](https://user-images.githubusercontent.com/21084423/35439083-286e0760-02d4-11e8-901a-be00de375866.png)
![2018-01-26 17 01 34](https://user-images.githubusercontent.com/21084423/35439084-28c496ac-02d4-11e8-8098-f846c2364847.png)
![2018-01-26 17 29 41](https://user-images.githubusercontent.com/21084423/35439085-2913797a-02d4-11e8-89b3-031e95206051.png)
![2018-01-26 17 49 05](https://user-images.githubusercontent.com/21084423/35439086-2964f8e0-02d4-11e8-8244-82fd889bb31c.png)

**Comment by MathGaron** [comment] 2018-01-26 13:44
Ok the issue seems to be with the normal buffer. 
Actually, you are not supposed to receive any NAN values in there, that would explain the weird triangles that you get as output I guess.

So first, make sure that you have the same model files (.ply) as the one on our website, and/or make sure that the 4 objects give you the same problem. If you still have the problem, then there is something wrong in the code.

As I told you earlier, I think I only tested with python3, so if you are using python2, it is possible that you get weird numerical bugs like this one.

If you still want to use python2 ( But I strongly suggest using python3!) the bug is potentially related to the line 50 in modelrenderer.ply. At this point, I normalize the normal vectors, and for some reason, the vector norm could be 0 which generate a division by zero error.

**Comment by MathGaron** [comment] 2018-01-26 18:08
Hey, 
I don't think it is a gpu related bug. I would focus on understanding why do the normals contain nan values.
So the bug seems to be related to the 3D model loading, and not with the rendering.

**Comment by Myzhencai** [comment] 2018-01-27 02:11
hi, @MathGaron ,according to your guide I just tested the "he bug is potentially related to the line 50 in modelrenderer.ply."here is the result it seems it is the overflow of this line make all issues.I try to change the type to np.float64 but failed with missing or with can not find nx, ny,nz .Do you think this is a issue with code or i just need to change the platform (gpu) for generate data?
![2018-01-27 08 37 04](https://user-images.githubusercontent.com/21084423/35467510-29ebe528-034a-11e8-8526-45dd5672614f.png)
![2018-01-27 08 38 17](https://user-images.githubusercontent.com/21084423/35467511-2a2048cc-034a-11e8-825d-c14e6dfe027d.png)
![2018-01-27 08 52 54](https://user-images.githubusercontent.com/21084423/35467512-2a54068a-034a-11e8-8849-52ae18bb07c2.png)
![Uploading 2018-01-27 08:58:01屏幕截图.png…]()
![Uploading 2018-01-27 09:00:16屏幕截图.png…]()
![Uploading 2018-01-27 09:06:47屏幕截图.png…]()
![Uploading 2018-01-27 09:07:48屏幕截图.png…]()
![Uploading 2018-01-27 09:08:26屏幕截图.png…]()
![Uploading 2018-01-27 09:11:26屏幕截图.png…]()
![Uploading 2018-01-27 09:22:09屏幕截图.png…]()
![Uploading 2018-01-27 09:27:10屏幕截图.png…]()
![Uploading 2018-01-27 09:29:05屏幕截图.png…]()
![Uploading 2018-01-27 09:34:02屏幕截图.png…]()
![Uploading 2018-01-27 09:35:53屏幕截图.png…]()
![Uploading 2018-01-27 09:40:38屏幕截图.png…]()
![Uploading 2018-01-27 09:42:18屏幕截图.png…]()
![Uploading 2018-01-27 09:44:33屏幕截图.png…]()
![Uploading 2018-01-27 09:46:12屏幕截图.png…]()

**Comment by MathGaron** [comment] 2018-01-27 14:18
I am not sure what you are printing in your screenshots, but it seems like it is the normals after calling plyparser. I am also not sure why there are more than 3 values on axis 1. That said, there are huge values that should not be there (xe-38). I will try to get some time today to reproduce this and update you later.

**Comment by Myzhencai** [comment] 2018-01-27 14:36
hi,the main of all the thing i did is that i first use the test.ply (made by myself ) to test the normals after calling plyparser then i print the normal after this code:
'''normals = normals / np.linalg.norm(normals, axis=1)[:, np.newaxis]'''
and no matter which ply file i change it still show the error like the image, but when i changed the code in plyparser in this code : 
"""
def get_vertex_normals(self):
        for element in self.data.elements:
            if element.name == "vertex":
                try:
                    return PlyParser.recarray_to_array(element.data[["nx", "ny", "nz"]], np.float32)(i changed it to np.float64)
"""
as you can see in the code i marked with red ,when i do not change it it show 3 number with warning ,when i changed it ,then it show 2 number without warning but missing one.
![image](https://user-images.githubusercontent.com/21084423/35472844-be830574-03b1-11e8-9785-a275a98bdfe2.png)

**Comment by Myzhencai** [comment] 2018-01-27 14:38
and sorry for that , i can not run in the workstation as i mentioned cause my classmates just make the system crashed by installing the cuda.oh my god!!

**Comment by MathGaron** [comment] 2018-01-27 15:19
Can you send your custom .ply, there is something wrong with it. The normals should be a Nx3 array with information about every vertex normals. Currently, I can't reproduce your bug.

**Comment by Myzhencai** [comment] 2018-01-27 15:59
OK，i will share to
you tomorrow will， acturely I just modified the geometry.ply of dragging. Change d the nubumer of element to 5 and the nx ny nz to 1 2  3 ...

**Comment by Myzhencai** [comment] 2018-01-27 16:06
And I just set print normal[0:1,I do not remember the data of this setting, but It just make the printing is just the three normal value]

**Comment by Myzhencai** [comment] 2018-01-28 02:19
`ply
format ascii 1.0
comment VCGLIB generated
element vertex 5
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
property uchar alpha
property float quality
element face 2
property list uchar int vertex_indices
end_header
-0.0758073 0.0147489 -0.00880594 1 2 3 191 191 191 255 0.19343 
-0.0757646 0.0144919 -0.00830121 4 5 6 175 175 175 255 0.177557 
-0.0761136 0.0143482 -0.00857608 7 8 9 192 192 192 255 0.193868 
-0.0761937 0.015855 -0.0102308 10 11 12 184 184 184 255 0.185957 
-0.0760448 0.0155081 -0.00982756 13 14 15 192 192 192 255 0.194475
3 39499 39298 39485 
3 37863 39485 39298`
![image](https://user-images.githubusercontent.com/21084423/35478313-946587a4-0414-11e8-9a4c-2de6a3d568f7.png)
just little change of the ao.ply for 3dmodels of dragon.

**Comment by Myzhencai** [comment] 2018-01-29 13:42
@MathGaron can you share your result of this ,thanks you a lot .maybe i should wait for you for some time today.

**Comment by MathGaron** [comment] 2018-01-29 16:45
I tried this same file, if I print the normals I get what is expected:

**Comment by Myzhencai** [comment] 2018-01-30 00:24
@MathGaron no i did not change anything ,what you shared is the first one normals right ,mine issue is about the second one .when i run the first one ,it is just like you did. but when i run the second one it shows the non and the warning of overflow .
        normals = plyparser.get_vertex_normals()
        normals = normals / np.linalg.norm(normals, axis=1)[:, np.newaxis]

**Comment by MathGaron** [comment] 2018-01-30 01:55
Can you give me your numpy's version? and your result of the normals right after the normalisation (after the second line)

**Comment by Myzhencai** [comment] 2018-01-30 13:35
@MathGaron Can this be a compiling issue that the np.float32 shared small restore memory for the caculated number??

**Comment by MathGaron** [comment] 2018-01-30 14:06
Ok I did not notice it at first, but you changed the normals array type to float64, while it should be read as an array of float32, that may explain the weird values you get in your arrays. Then your normals should be computed normally. linalg should not have any 0s or huge values.

**Comment by Myzhencai** [comment] 2018-01-30 14:20
@MathGaron  hi， you seems misunderstanding what i said , if i did not change the float32 and i get the first two pics, if i changed it i get the last 2 pics.so i guess it is the issue of compiling. : -)

**Comment by Myzhencai** [comment] 2018-01-30 14:25
@MathGaron should i change float32 to float64 ? if i do,it seems i will lost a data .

**Comment by Myzhencai** [comment] 2018-01-30 14:30
the same issue occurred when i changed to a new gpu,this should be dependence or complie issue

**Comment by MathGaron** [comment] 2018-01-30 14:49
The GPU as nothing to do with the .ply loading, I have tested with the same numpy version, on different versions of python and everything seems to work on my side.

So first, the array have to be shaped like a float32, else you will have a bug. Also, I saw that you are printing with normals[0:5, -5:-2]. There is something wrong here, the normal array is supposed to be an nx3 as I specified earlier, this could be the reason why linalg.norm fails. 

I would recommend you to download the code/dataset again to make sure that you start from a fresh version. I will close this issue as I am unable to replicate your bug.

**Closed by MathGaron** 2018-01-30 14:49 UTC

**Comment by Myzhencai** [comment] 2018-01-30 15:53
OK，thanks

**Comment by Myzhencai** [comment] 2018-01-31 03:00
@MathGaron  can you share the plyfile version?

**Comment by MathGaron** [comment] 2018-01-31 12:07
I am using 0.4, I see that there is a 0.5 version that I never tested, are you using the same version? You still have the same problem after recloning the repo and downloading the datasets?

**Comment by Myzhencai** [comment] 2018-01-31 13:37
well I use the 0.5 version,and i just pip install it.can this be the reason? Maybe I will have a test tommorrow ,I think my issue is just the plyparser issue ,so I will focus on it.

**Comment by Myzhencai** [comment] 2018-01-31 13:40
yeah , same issues , I have made up a wiki for your project ,if you think it is useful maybe you can put it in your wiki or readme to make everything specify : -).
https://github.com/Myzhencai/deeptracking/wiki/ALL-DETAILS-OF-deeptracking-project.

**Comment by MathGaron** [comment] 2018-01-31 13:58
Ok well, I would definitely try 0.4 as 0.5 seems to have some breaking changes, and indeed the problem seems to be related to the ply file reading. Tell me about it so I can update the documentation.

In your wiki, you should maybe mention that you had some difficulty generating the data, thus without data, you can not expect a proper training.

Also, there is currently a docker file in the project for the training part, but none for the dataset generation, which could be a nice add-on/documentation for the installation process.

**Comment by Myzhencai** [comment] 2018-01-31 14:55
i yesterday have generated the docker images for almost all the dependences but I failed to commit it ,just a few days (tomorrow I will go back home from school,)I will push it to the docket hub and share to you . It is just based your docker images

**Comment by Myzhencai** [comment] 2018-02-01 09:10
@MathGaron  same things happen even changed the version to 0.4 maybe i need to modify the plyfile

**Comment by Myzhencai** [comment] 2018-02-01 14:35
@MathGaron  I just installed the dependences for the plyparser.py and test it with the file in this part : https://github.com/mingliangfu/deeptracking/blob/master/tests/data/basic.ply
and this part : https://github.com/mingliangfu/deeptracking/blob/master/tests/data/basic_color.ply
and the first one is normal but the second one is weired , maybe you can have a test .here is the result of mine:plyfile version 0.4
![screenshot from 2018-02-01 21 59 37](https://user-images.githubusercontent.com/21084423/35683770-f3f9117a-079f-11e8-87fd-e2e76e008239.png)
![screenshot from 2018-02-01 22 01 18](https://user-images.githubusercontent.com/21084423/35683772-f430d056-079f-11e8-8cb1-d8143f5a405f.png)
![Uploading Screenshot from 2018-02-01 22:02:29.png…]()

**Comment by Myzhencai** [comment] 2018-02-06 13:48
@MathGaron  hi , thanks for help I finally find that it is the version of numpy that make the issue ,we can not just pip the numpy because the numpy=1.14.0 will make the error . have a nice day

**Comment by MathGaron** [comment] 2018-02-06 15:01
Ok good catch, I will document this. Thank you for the update!
